FROM centos/basic

MAINTAINER Kala Liu(email:kalaliu@aaxischina.com)

ENV HOSTNAME localhost
#Update the hosts
RUN echo "127.0.0.1 endeca.workbench endeca.mdex" >> /etc/hosts

ENV DOWNLOAD_SERVER http://172.17.3.91/

#Attach the installation package to container
RUN mkdir /softwares
WORKDIR   /softwares

RUN for plugin in java/jdk1.6.0_34.zip \
                  jboss/jboss-5.1.0.GA.zip \
                  ant/apache-ant-1.7.1.zip \
                  oracle/oracle-instantclient11.2-basic-11.2.0.1.0-1.x86_64.zip \
                  oracle/oracle-instantclient11.2-sqlplus-11.2.0.1.0-1.x86_64.zip ;\
       do echo "start downloading ${plugin}" && wget -q $DOWNLOAD_SERVER/apps/${plugin} ; done 

RUN echo "downloading ATG" && wget -q $DOWNLOAD_SERVER/apps/atg/atg10.2.zip
RUN chmod -R 755 /softwares

#Create the user docker
RUN useradd docker \
   && echo -e "docker\ndocker" | passwd docker

#Add the user docker into sudoer
RUN echo "docker        ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers

#Begin the install
#Install JAVA
RUN mkdir /opt/java \
    && unzip -q /softwares/jdk1.6.0_34.zip -d /opt/java \
    && chown -R docker:docker /opt/java \
    && chmod -R 755 /opt/java \
    && ln -s /opt/java/jdk1.6.0_34 /opt/java/jdk


USER docker
ENV JAVA_HOME /opt/java/jdk
ENV PATH $JAVA_HOME/bin:$PATH 
RUN echo "export JAVA_HOME=/opt/java/jdk" >> /home/docker/.bash_profile \
    && echo "export PATH=/opt/java/jdk/bin:$PATH" >> /home/docker/.bash_profile \
    && source /home/docker/.bash_profile

#Install JBOSS
USER root
RUN mkdir /opt/jboss \
    && unzip -q /softwares/jboss-5.1.0.GA.zip -d /opt/jboss \
    && chown -R docker:docker /opt/jboss \
    && chmod -R 755 /opt/jboss
USER docker
ENV JBOSS_HOME /opt/jboss/jboss-5.1.0.GA
ENV JBOSS_VERSION 5.1.0.GA
RUN echo "export JBOSS_HOME=/opt/jboss/jboss-5.1.0.GA" >> /home/docker/.bash_profile \
    && echo "export JBOSS_VERSION=5.1.0.GA" >> /home/docker/.bash_profile \
    && source /home/docker/.bash_profile

#Install ANT
USER root
RUN mkdir /opt/ant \
    && unzip -q /softwares/apache-ant-1.7.1.zip -d /opt/ant \
    && chown -R docker:docker /opt/ant \
    && chmod -R 755 /opt/ant
USER docker
ENV ANT_HOME /opt/ant/apache-ant-1.7.1
ENV ANT_OPTS "-Xms768m -Xmx1024m -XX:PermSize=128m -XX:MaxPermSize=768m"
ENV PATH $ANT_HOME/bin:$PATH
RUN echo "export ANT_HOME=/opt/ant/apache-ant-1.7.1" >> /home/docker/.bash_profile \
    && echo "export ANT_OPTS=\"-Xms768m -Xmx1024m -XX:PermSize=128m -XX:MaxPermSize=768m\"" >> /home/docker/.bash_profile \
    && echo "export PATH=/opt/ant/apache-ant-1.7.1/bin:$PATH" >> /home/docker/.bash_profile \
    && source /home/docker/.bash_profile


#Install oracleclient
USER root
RUN mkdir -p /opt/oracleclient \
    && unzip -q /softwares/oracle-instantclient11.2-basic-11.2.0.1.0-1.x86_64.zip -d /opt/oracleclient \
	&& unzip -q /softwares/oracle-instantclient11.2-sqlplus-11.2.0.1.0-1.x86_64.zip -d /opt/oracleclient \
	&& chown -R docker:docker /opt/oracleclient
USER docker	
ENV ORACLE_HOME /opt/oracleclient/instantclient_11_2
ENV LD_LIBRARY_PATH /opt/oracleclient/instantclient_11_2
ENV PATH /opt/oracleclient/instantclient_11_2:$PATH
RUN echo "export ORACLE_HOME=/opt/oracleclient/instantclient_11_2" >> /home/docker/.bash_profile \
	&& echo "export LD_LIBRARY_PATH=/opt/oracleclient/instantclient_11_2" >> /home/docker/.bash_profile \
	&& echo "export PATH=/opt/oracleclient/instantclient_11_2:$PATH" >> /home/docker/.bash_profile \
	&& source /home/docker/.bash_profile



#Install ATG
USER root
RUN unzip -q /softwares/atg10.2.zip -d /opt/ATG/ && chown -R docker:docker /opt/ATG
RUN echo "ATGJRE=/opt/java/jdk/bin/java;export ATGJRE" > /opt/ATG/ATG10.2/home/localconfig/dasEnv.sh \
    && echo "JBOSS_HOME=/opt/jboss/jboss-5.1.0.GA;export JBOSS_HOME" >> /opt/ATG/ATG10.2/home/localconfig/dasEnv.sh \
    && echo "JBOSS_VERSION=5.1.0.GA;export JBOSS_VERSION" >> /opt/ATG/ATG10.2/home/localconfig/dasEnv.sh
USER docker
ENV DYNAMO_ROOT /opt/ATG/ATG10.2
ENV DAS_ROOT /opt/ATG/ATG10.2
ENV DYNAMO_HOME $DYNAMO_ROOT/home
ENV ATGJRE $JAVA_HOME/bin/java
RUN echo "export DYNAMO_ROOT=/opt/ATG/ATG10.2" >> /home/docker/.bash_profile \
    && echo "export DAS_ROOT=/opt/ATG/ATG10.2" >> /home/docker/.bash_profile \
    && echo "export DYNAMO_HOME=/opt/ATG/ATG10.2/home" >> /home/docker/.bash_profile \
    && echo "export ATGJRE=/opt/java/jdk/bin/java" >> /home/docker/.bash_profile \
    && source /home/docker/.bash_profile



#Clean the yum
USER root
RUN yum clean all

#Remove the install sources
RUN rm -rf /softwares/*

#Expose ports
EXPOSE 22 8080 8180 8280 8380 8787 8009

WORKDIR /

CMD ["/usr/sbin/sshd", "-D"]
