#!/bin/bash
# endeca: Start/Stop jenkins
#
# chkconfig: 345 99 01
# description: start/stop jenkins
#
# processname: jenkins
 
. /etc/rc.d/init.d/functions
 
DESC="Jenkins CI Server"
NAME=jenkins
JENKINS_ROOT=/opt/jenkins
JENKINS_HOME=$JENKINS_ROOT/home
LOGFILE=$JENKINS_ROOT/log/jenkins.log
JENKINS_WAR=$JENKINS_ROOT/jenkins.war
JAVA_HOME=/opt/java/jdk
JENKINS_OPT="-Djava.awt.headless=true --httpPort=18080 --ajp13Port=18009 --debug=5 --handlerCountMax=100 --handlerCountMaxIdle=20"


d_start() {
        if $(ps -ef | grep -q $JENKINS_WAR | grep -v grep);then
           ps -ef | grep -w $JENKINS_WAR | grep -v grep | awk '{print $2}' | xargs kill -9
        fi
        echo "Starting $DESC..."
        nohup $JAVA_HOME/bin/java -DJENKINS_HOME=$JENKINS_HOME -jar $JENKINS_WAR --logfile=$LOGFILE --webroot=$JENKINS_ROOT/war $JENKINS_OPT >/dev/null &
}
 
d_stop() {
        if $(ps -ef | grep -q $JENKINS_WAR);then
           ps -ef | grep -w $JENKINS_WAR | grep -v grep | awk '{print $2}' | xargs kill -9
        else
           echo "$DESC is not running..."
        fi
}

case $1 in
  start)
    echo "Starting $DESC: $NAME"
    d_start
    ;;
  stop) 
    echo "Stopping $DESC: $NAME"
    d_stop
    ;;
  restart)
    echo  "Restarting $DESC: $NAME"
  d_stop
    sleep 1
    d_start
    ;;
  *)
    echo "usage: $NAME {start|stop|restart}"
    exit 1
    ;;
esac
exit 0
